apiVersion: v1
kind: Service
metadata:
  name: goapp-service
  labels:
    app: goapp
spec:
  type: NodePort #LoadBalancer, ClusterIP, NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: goapp
