POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json

{
    "name": "My Product 3",
    "price": 100
}

###
GET http://localhost:8000/products/6dba1d1a-2089-4f5c-af73-e1ce4909a7c3 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:8000/products/6dba1d1a-2089-4f5c-af73-e1ce4909a7c3 HTTP/1.1
Content-Type: application/json

{
    "name": "My Product 4",
    "price": 150
}

###
DELETE http://localhost:8000/products/6dba1d1a-2089-4f5c-af73-e1ce4909a7c3 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8000/products?page=1&limit=10&sort=asc HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8000/products?page=1&limit=10&sort=desc HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTk2MTc0NTYsInVzZXJfaWQiOiI1ODE2YWZhYy03YTRjLTRiMDMtYWVlMS05MzI3ZGM3OWZiYWYifQ.ZqG8G50xcc0I-X-eOVgl6YRIR1zI574OMmFoC7bXTjI

###